server:
  port: 9090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: document-service
          uri: http://localhost:9092
          predicates:
            - Path=/api/document/**
          filters:
            - RemoveRequestHeader=Cookie

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

jwt:
  secret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCB2YWxpZCBCYXNlNjQga2V5Lg==
